version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    environment:
     - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '54320:5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'

  redis:
    image: redis:6.0.9-alpine
    ports:
      - '63790:6379'
    command: 'redis-server --appendonly yes'
    volumes:
      - 'redis_data:/data'

volumes:
  db_data:
  redis_data:
